from pathlib import Path
from datetime import date
from html import escape as e
from urllib.parse import quote
import json
ROOT=Path(__file__).resolve().parent.parent
# All times are suggested local-time windows, not reservations.
days=[
('la',9,'A soft landing in Los Angeles','Arrival · Hollywood','Easy start','Los Angeles',[
('Afternoon','Land, settle in, exhale.','Allow for immigration, luggage and LA traffic. Check into your hotel, eat something easy and keep the afternoon free until your actual arrival time is known.'),
('If you have energy','A little Hollywood.','Make a short visit to the Walk of Fame and TCL Chinese Theatre. Think of this as a quick first look, rather than a whole afternoon. Skip it if you arrive late.'),
('Evening','Dinner close to home.','An easy taco dinner and an early night. Tomorrow has the big views; there is no need to chase a sunset straight off a long flight.')],
'Base yourself in West Hollywood or Hollywood for all three nights. West Hollywood is a pleasant dinner base; Hollywood can be convenient for sightseeing. Check the exact hotel location and recent reviews.',
'Late arrival? Go straight to the hotel. Nothing essential is booked today.',['TCL Chinese Theatre','West Hollywood, Los Angeles'],[]),
('la',10,'The LA you came to see','Beverly Hills · The Grove · Griffith','Classic LA','Los Angeles',[
('10:00–12:00','Coffee, palms & Rodeo Drive.','Start in Beverly Hills: a café breakfast, Beverly Gardens Park and a relaxed Rodeo Drive stroll. Enjoy the architecture and window-shopping without needing a designer-shopping budget.'),
('12:30–15:30','Lunch at the market. A little shopping.','Head to the Original Farmers Market beside The Grove for lunch, then browse the outdoor shops. If independent boutiques appeal more, swap The Grove for Melrose Avenue; choose one shopping area rather than crossing town repeatedly.'),
('17:30–evening','Griffith at golden hour.','Head to Griffith Observatory for the Hollywood Sign view and the city lighting up. Leave plenty of traffic time. The grounds and building are free; check hours if you want to go inside. Finish with dinner in Los Feliz or near your hotel.')],
'Keep Hollywood Boulevard a short photo stop on arrival day. Today is about the more enjoyable mix of cafés, neighborhoods and a genuinely memorable sunset. Rideshares let you avoid parking; allow a generous cross-city buffer.',
'If movie sets and rides are your biggest interest, Universal Studios Hollywood can replace this whole daytime plan. It deserves a full day; do not squeeze it between shopping stops.',['Beverly Gardens Park','Rodeo Drive','The Original Farmers Market Los Angeles','The Grove Los Angeles','Griffith Observatory'],[('The Grove shops & dining','https://thegrovela.com/'),('Griffith visitor information','https://griffithobservatory.lacity.gov/visit/'),('Optional Universal day','https://www.universalstudioshollywood.com/web/en/us')]),
('la',11,'Salt air, beach bikes & a Pacific sunset','Venice · Abbot Kinney · Santa Monica','California beach day','Los Angeles',[
('10:00–12:30','Venice, before the afternoon rush.','Walk the Venice canals, see the beach and skatepark, then head to Abbot Kinney Boulevard for coffee and boutiques. Keep it leisurely: this is a day to feel California, not just photograph it.'),
('12:30–16:00','Lunch, then follow the ocean.','Have lunch around Abbot Kinney. Rent a bike from a local shop if you feel like riding the beach path toward Santa Monica; confirm the return location and closing time. Walking part of the path or taking a short rideshare also works.'),
('Late afternoon–sunset','Santa Monica Pier & a beach dinner.','Spend time on the sand, visit the pier and decide whether a ride is worth it for the view. Stay for sunset, then dinner near the ocean before returning to your LA hotel.')],
'The core day stays on the west side, with no long coastal drive. If Malibu is a must, make it a morning replacement for Venice and arrange transport in advance; do not add Santa Barbara to this day.',
'Cool or cloudy beach weather still works for the canals, cafés and shopping. If coastal road travel is added, check live access before leaving.',['Venice Canals','Venice Skatepark','Abbot Kinney Boulevard','Santa Monica Pier'],[('California road conditions if adding Malibu','https://quickmap.dot.ca.gov/')]),
('vegas',12,'Trade palm trees for neon','Los Angeles → Las Vegas','Travel day','Las Vegas',[
('Morning','One last LA breakfast.','Pack and leave a generous airport buffer. If you hired a car, allow extra time for fuel, rental return and the terminal transfer. Choose LAX or Burbank based on the actual flight and your hotel.'),
('Midday / afternoon','Fly to Las Vegas.','A nonstop flight is roughly 1–1.5 hours in the air; allow a half day door to door. LA and Las Vegas share Pacific time. Check in and take a break before heading out.'),
('Evening','The Strip, for the first time.','Start around Bellagio: see the conservatory, catch the fountains if operating and wander toward Caesars Palace. Save the Venetian and other resorts for tomorrow instead of walking the entire Strip tonight.')],
'Stay on the central Strip for three nights. Compare the total including resort fees, taxes and deposits. Distances between resorts are much longer than they look.',
'If the flight is delayed, a single Bellagio stop and dinner are enough.',['Harry Reid International Airport','Bellagio Las Vegas','Caesars Palace'],[]),
('vegas',13,'Poolside, then all dressed up','Pool · Venetian · Sphere · Optional nightlife','The Vegas day','Las Vegas',[
('Late morning','A proper pool morning.','Sleep in, have brunch and enjoy your hotel pool. If a dayclub sounds fun, consider Marquee at the Cosmopolitan instead of the hotel pool and check Sunday’s actual event, admission and dress rules before booking.'),
('Afternoon','Venetian canals & a little shopping.','Explore the Venetian and its indoor canals, stop for lunch or a snack and browse the Grand Canal Shoppes. Leave time to go back to the hotel and get ready.'),
('Evening','Dinner, then Sphere.','Pick a performance actually listed for September 13, with dinner timed around it. The Wizard of Oz is one current Sphere option to investigate. If you want dancing afterward, choose a venue by that night’s music and event calendar; it is optional, not another obligation.')],
'This is the main Vegas night out. Spend on the experience you actually want: a good show, a dayclub or a club ticket. There is no need to buy all three. Check the final ticket total and seat view, and arrange the ride home.',
'If the preferred Sphere performance is on Monday instead, swap evenings. If shows are not her thing, make dinner and a music-led night out the headline.',['The Venetian Las Vegas','Grand Canal Shoppes','Sphere Las Vegas'],[('Sphere official dates & tickets','https://www.thesphere.com/shows/calendar'),('Marquee dayclub calendar','https://taogroup.com/venues/marquee-dayclub-las-vegas/events/'),('OMNIA nightlife calendar','https://taogroup.com/venues/omnia-nightclub-las-vegas/events/')]),
('vegas',14,'Slow brunch. Downtown neon.','Brunch · Resort time · Fremont Street','Easy day, bright evening','Las Vegas',[
('Late morning','Recover at your own pace.','A late breakfast, a swim or coffee and people-watching. This morning stays open after Sunday night.'),
('Afternoon','Choose your kind of Vegas.','Keep it relaxed with a resort wander and shopping, or choose an immersive art experience such as Meow Wolf’s Omega Mart at AREA15 if that sounds more fun. Check timed tickets and allow travel time; it replaces the resort afternoon.'),
('Evening','Fremont Street after dark.','Take a rideshare downtown for the illuminated canopy, music and old-school Vegas energy. SlotZilla is an optional zipline if you want an adrenaline moment. Have dinner, then head back and pack for tomorrow’s flight.')],
'Fremont Street is a separate downtown outing, not an easy continuation of a Strip walk. Keep the last evening moderate so the morning flight to New York is manageable.',
'If Sphere moved here, use the afternoon to relax and skip Fremont rather than rushing both.',['Fremont Street Experience','SlotZilla Las Vegas'],[('Fremont Street & SlotZilla','https://vegasexperience.com/'),('Optional Omega Mart','https://meowwolf.com/visit/las-vegas')]),
('nyc',15,'Hello, New York','Las Vegas → NYC · Times Square','Travel day','New York City',[
('Morning','Fly east.','Choose a morning nonstop if possible. The flight takes roughly 5 hours and New York is 3 hours ahead, so much of the day disappears. Check whether you land at JFK, LaGuardia or Newark.'),
('Late afternoon / evening','Hotel, food, a little reset.','Allow for baggage and the airport transfer before committing to plans. Use the appropriate airport’s official transport guidance; the three airports have different routes.'),
('After dark','Your Times Square moment.','If arrival allows, make a short visit to Times Square. Get the photos, take in the lights and have dinner. Save the full sightseeing day for tomorrow.')],
'Use one NYC hotel for eight nights. Midtown West, Chelsea or a well-connected Midtown location makes a practical base. Compare total hotel costs, subway access and recent reviews before choosing.',
'Late flight? Move Times Square to another evening. There is no paid reservation today.',['Times Square, New York'],[('NYC airport transport','https://www.panynj.gov/airports/en/index.html')]),
('nyc',16,'Get your bearings. Then take flight.','Midtown · NYC helicopter · Seaport','Must-do flight','New York City',[
('09:00–11:30','A first look at Manhattan.','Choose an optional hop-on/hop-off bus introduction, or a shorter walk around Midtown. If taking the bus, check today’s route and stops; it is sightseeing, not a reliable transfer to your flight.'),
('Early afternoon','The skyline from the Hudson.','Aim for a HeliNY Downtown Manhattan departure, such as its 17–20 minute Ultimate Tour. Reach the heliport independently, allowing transit time plus the required check-in. Confirm the exact address on your reservation.'),
('Late afternoon / evening','Seaport & the waterfront.','Keep the rest of the day nearby: a Seaport stroll, waterfront views and a relaxed dinner. The helicopter is the headline; no need to race straight to the opposite end of Manhattan.')],
'Book early in the NYC stay for weather flexibility. Downtown sightseeing routes follow the river for skyline views; they are not flights between Midtown buildings. HeliNY also sells New Jersey departures—check the departure location carefully.',
'Weather cancellation? Move the flight to September 18 or 22, subject to availability. Those days have flexible walking plans.',['Downtown Manhattan Heliport','South Street Seaport'],[('NYC helicopter tours & fees','https://heliny.com/'),('Optional sightseeing bus','https://www.bigbustours.com/en/new-york/new-york-bus-tours')]),
('nyc',17,'Meet Lady Liberty','Liberty Island · Ellis Island · Lower Manhattan','Book ahead','New York City',[
('08:30–09:30 target','Ferry from The Battery.','Reserve a morning Statue City Cruises departure from New York, not New Jersey. Follow the ticket’s screening and arrival instructions. The selected ticket time relates to entry into screening, not a guaranteed ferry departure.'),
('Morning / early afternoon','Liberty Island & Ellis Island.','Allow about 4–5 hours overall, longer for deep museum visits. Choose pedestal or crown only if available and suitable; the standard island visit is still worthwhile. Ellis Island adds context to America’s immigration story.'),
('Late afternoon','Lower Manhattan, at your pace.','If energy allows, walk past Wall Street and visit the outdoor 9/11 Memorial respectfully. The museum is a separate, longer visit. Skip an extra observation deck; Top of the Rock is already planned.')],
'Statue City Cruises is the only authorized ferry that lands visitors on both islands. Book through the official NPS link. Pedestal and crown inventory is limited; do not buy a harbor sightseeing cruise expecting island access.',
'If island tickets are sold out, a harbor sightseeing cruise can give views but is not a substitute for landing. Keep checking official availability.',['The Battery, New York','Wall Street, New York','9/11 Memorial'],[('Official ferry & ticket guidance','https://www.nps.gov/stli/planyourvisit/fees.htm'),('Screening & arrival information','https://www.nps.gov/stli/planyourvisit/index.htm')]),
('nyc',18,'The city, with room to wander','Chelsea · High Line · West Village','Flexible / flight backup','New York City',[
('10:00–12:00','Chelsea Market lunch crawl.','Start with coffee and browse the food stalls. Pick lunch when something looks good instead of building the day around a hard-to-get reservation.'),
('13:00–16:00','High Line & Little Island.','Walk a manageable stretch of the High Line, then head toward Little Island. Stop for river views, take breaks and check park access before setting off.'),
('Evening','West Village dinner.','Wander the smaller streets, see Washington Square Park and find dinner in the Village. Reserve ahead if there is a particular restaurant you really want.')],
'This is the first NYC helicopter backup day. If the flight moves here, shorten Chelsea and take transit to the confirmed departure location rather than trying to walk the whole route.',
'Rain? Replace the outdoor walk with a museum visit or a long Chelsea Market lunch.',['Chelsea Market','The High Line','Little Island NYC','Washington Square Park'],[('High Line hours & access','https://www.thehighline.org/visit/'),('Little Island visitor information','https://littleisland.org/visit-us/')]),
('nyc',19,'Park greens, skyline gold','Central Park · Fifth Avenue · Top of the Rock','One great observation deck','New York City',[
('09:30–12:30','A slow Central Park morning.','Walk the Mall, Bethesda Terrace and Bow Bridge. Take a coffee break and leave time simply to sit. You do not need to cover the entire park.'),
('14:00–16:30','Fifth Avenue icons.','Head south for Fifth Avenue, St. Patrick’s Cathedral and Rockefeller Center. This groups the sights naturally without repeated subway trips.'),
('Late afternoon / sunset','Top of the Rock.','Reserve a time before sunset if the forecast is good. You get the Empire State Building in the skyline rather than standing inside it. Sunset slots can cost more and fill up.')],
'One observation deck is enough alongside the helicopter. Pick a clear-weather time over a rigid schedule; check the ticket’s change policy before paying.',
'Poor visibility? Swap the deck with a clearer day if your ticket permits. Browse Midtown or visit an indoor museum instead.',['Bethesda Terrace','Bow Bridge','St. Patrick’s Cathedral New York','Top of the Rock'],[('Top of the Rock official tickets','https://www.rockefellercenter.com/tickets/top-of-the-rock-observation-deck')]),
('nyc',20,'Across the bridge, into Brooklyn','Brooklyn Bridge · DUMBO · Waterfront','Photo day','New York City',[
('09:00–10:30','Walk the Brooklyn Bridge.','Start on the Manhattan side and cross to Brooklyn. Go early for a calmer walk, keep the path clear for others and leave plenty of time for photos.'),
('11:00–15:00','DUMBO & Brooklyn Bridge Park.','Find the Washington Street view, have lunch around DUMBO and wander the waterfront. Take photos from the sidewalk rather than standing in traffic.'),
('Late afternoon / evening','The skyline from the other side.','Continue to Brooklyn Heights Promenade if your feet are happy. Stay for the light changing over Manhattan, then take the subway or a ferry with a confirmed return route.')],
'Wear your most comfortable shoes. A ferry can be a lovely finish, but check the current route and last departure first; NYC Ferry uses separate tickets from the subway.',
'If it rains heavily, move this walk to September 22 and use today for an indoor choice.',['Brooklyn Bridge Manhattan entrance','Washington Street DUMBO','Brooklyn Bridge Park','Brooklyn Heights Promenade'],[('NYC Ferry routes & tickets','https://www.ferry.nyc/')]),
('nyc',21,'Art, architecture, a New York evening','The Met · Grand Central · Bryant Park','Culture day','New York City',[
('10:00–13:00','Choose a few galleries at The Met.','Spend the morning at the Metropolitan Museum of Art. Choose two or three collections rather than trying to see everything. Monday fits its published weekly schedule; the museum is closed Wednesdays.'),
('14:30–17:00','Grand Central & Bryant Park.','Take transit to Grand Central, then walk to Bryant Park and the New York Public Library’s main building. Check visitor access and tour times if you want to go inside.'),
('Evening','Dinner & a rooftop view.','Have dinner, then try a rooftop such as 230 Fifth for the Empire State Building backdrop if the weather is good. Check that evening’s opening and entry rules. A mocktail and the view are just as much the point as a cocktail.')],
'The Met is the default museum choice. If natural history appeals more, swap in the American Museum of Natural History and check its entry requirements. Avoid scheduling both museums in one day.',
'This is also a good rainy-day plan to exchange with September 19 or 20, provided the chosen museum is open.',['The Metropolitan Museum of Art','Grand Central Terminal','Bryant Park'],[('The Met visitor information','https://www.metmuseum.org/plan-your-visit'),('NYPL visitor information','https://www.nypl.org/locations/schwarzman'),('230 Fifth rooftop','https://230-fifth.com/')]),
('nyc',22,'One more neighborhood. One big finale.','SoHo · Chinatown · Broadway','Flexible day + curtain call','New York City',[
('Late morning','SoHo, without a checklist.','Coffee, shopping, cast-iron streets and time to explore. This is intentionally a loose morning for whatever you still want to do.'),
('Afternoon','Chinatown lunch, or your missed favorite.','Walk to Chinatown for lunch and pass through Little Italy if you are curious. Alternatively use the daytime for a rescheduled helicopter, Brooklyn walk or a favorite place you want to revisit.'),
('Evening','Your Broadway night.','Book a Tuesday performance through the show’s official ticket link. Choose a story or music you already like; a visual musical can be a fun first choice. Eat nearby and arrive according to the theater’s guidance.')],
'Protect the show’s curtain time when rearranging the day. The Broadway League’s directory links to official show sites; the exact performance and ticket availability still need confirmation.',
'If your preferred show is unavailable, choose another listed Tuesday performance or move Broadway to an earlier evening after checking its calendar.',['SoHo New York','Chinatown Manhattan','Theater District Manhattan'],[('Broadway official show directory','https://www.broadway.org/')]),
('nyc',23,'A last coffee, then home','NYC → onward journey','Departure day','Departure',[
('Morning, if time permits','One small goodbye.','Breakfast near the hotel and a short local walk. Keep luggage storage and checkout in mind. No major attraction or nonrefundable booking today.'),
('Before your flight','Give the airport its time.','Build the transfer around your actual departure airport and airline guidance. For an international flight, plan to reach the airport around 3 hours early, with travel time and a traffic buffer added on top.'),
('If leaving late','A bonus few hours.','Use any genuine spare time for a nearby café, a final shop or a familiar park. Return to collect luggage well before your planned airport transfer.')],
'The trip ends September 23 in this plan, following the requested dates. If the flight is actually September 24, September 23 becomes a full flexible day and one extra hotel night is needed.',
'An early flight means breakfast to go and a direct airport transfer.',['New York City'],[])
]
chapters=[('la','01','Los Angeles','Pacific days. Hollywood nights.','September 9–12 · 3 nights','la.jpg','Palm-lined Los Angeles streets beneath a bright sky','Cafés, Beverly Hills, a Griffith sunset and a whole day by the Pacific.'),('vegas','02','Las Vegas','Turn the lights all the way up.','September 12–15 · 3 nights','vegas.jpg','Las Vegas Strip glowing after dark','Pool time, a standout show and a night under the downtown neon.'),('nyc','03','New York City','The city you already know by heart.','September 15–23 · 8 nights','nyc.jpg','Manhattan skyline across the water','Eight nights for the icons, the neighborhoods and the little things in between.')]

def link(label,url): return f'<a href="{e(url,quote=True)}" target="_blank" rel="noopener noreferrer">{e(label)} <span aria-hidden="true">↗</span></a>'
def render_day(d):
    region,day,title,route,tag,stay,slots,note,backup,places,links=d
    dt=date(2026,9,day)
    timeline=''.join(f'<li><span class="time">{e(t)}</span><div><h4>{e(h)}</h4><p>{e(p)}</p></div></li>' for t,h,p in slots)
    maplinks=''.join(link(p,'https://www.google.com/maps/search/?api=1&query='+quote(p)) for p in places)
    return f'''<details class="day" id="day-{day}" {'open' if day in (9,12,15) else ''}>
<summary><span class="date"><b>{day:02}</b><span>SEP · {dt.strftime('%a').upper()}</span></span><span class="day-heading"><span class="day-route">{e(route)}</span><h3>{e(title)}</h3></span><span class="tag">{e(tag)}</span><span class="toggle" aria-hidden="true">+</span></summary>
<div class="day-content"><ol class="timeline">{timeline}</ol><aside class="day-aside"><span class="eyebrow">MAKE IT WORK</span><p>{e(note)}</p><div class="backup"><b>Keep it flexible</b><p>{e(backup)}</p></div><span class="stay">◷ &nbsp; Overnight: {e(stay)}</span></aside><div class="day-links"><div><b>Places on the map</b><div>{maplinks}</div></div>{('<div><b>Plan & book</b><div>'+''.join(link(l,u) for l,u in links)+'</div></div>') if links else ''}</div></div></details>'''

chapterhtml=''
for key,num,name,title,dates,img,alt,intro in chapters:
    chapterhtml+=f'''<section class="chapter" id="{key}" aria-labelledby="heading-{key}"><div class="chapter-head"><div><span class="eyebrow">CHAPTER {num} / {e(dates).upper()}</span><h2 id="heading-{key}">{e(name)}<span class="dot">.</span></h2><p>{e(intro)}</p></div><a class="back" href="#route">Back to route ↑</a></div><div class="chapter-banner"><img src="assets/{img}" alt="{e(alt)}" loading="lazy" width="1600" height="1000"><p>{e(title)}</p></div><div class="day-list">{''.join(render_day(d) for d in days if d[0]==key)}</div></section>'''
bookings=[('01','Statue of Liberty','September 17','Start with official island tickets. Choose New York departure; pedestal or crown only if available. Standard island access is a good fallback.','Official ticket guidance','https://www.nps.gov/stli/planyourvisit/fees.htm'),('02','Manhattan from the sky.','NYC · September 16','The trip’s helicopter ride. Confirm a Manhattan departure, total charges and weather policy. Keep September 18 or 22 available for a weather reschedule.','NYC operator','https://heliny.com/'),('03','Two unforgettable evenings.','Vegas Sep 13 · Broadway Sep 22','Choose a Sphere performance or a music-led Vegas night out, then a Broadway show you will enjoy. Confirm actual dates before booking; leave travel evenings flexible.','Broadway shows','https://www.broadway.org/'),('04','The golden-hour skyline','September 19','Top of the Rock is the one planned observation deck. Check the weather and ticket-change policy before choosing your time.','Official deck tickets','https://www.rockefellercenter.com/tickets/top-of-the-rock-observation-deck')]
bookinghtml=''.join(f'<article class="booking"><span class="booking-num">{n}</span><span class="eyebrow">{e(dt)}</span><h3>{e(title)}</h3><p>{e(desc)}</p>{link(label,url)}</article>' for n,title,dt,desc,label,url in bookings)
cards=''.join(f'<a class="destination {key}" href="#{key}"><img src="assets/{img}" alt="{e(alt)}" width="1600" height="1000" {"fetchpriority=\"high\"" if key=="la" else ""}><span class="card-top"><span>CHAPTER {num}</span><span>↗</span></span><span class="card-bottom"><span>{e(dates)}</span><strong>{e(name)}</strong></span></a>' for key,num,name,title,dates,img,alt,intro in chapters)
html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#172c36"><title>America, for the first time — September 9–23, 2026</title><meta name="description" content="A 15-day journey through Los Angeles, Las Vegas and New York. A thoughtful daily itinerary with an NYC helicopter ride, the Statue of Liberty, beach days and city nights."><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;600;650;700&family=Manrope:wght@400;500;600;700;800&family=Playfair+Display:ital,wght@1,500&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head>
<body><a class="skip" href="#itinerary">Skip to daily itinerary</a><header><a class="brand" href="#top"><span class="brand-mark">a<span>↗</span></span> THE AMERICA EDIT</a><nav aria-label="Main navigation"><a href="#route">The route</a><a href="#itinerary">Day by day</a><a href="#bookings">Book ahead</a><a href="#essentials">Good to know</a></nav><button class="print-button" type="button" id="print">Print guide <span aria-hidden="true">↗</span></button></header>
<main id="top"><section class="intro" id="route"><div class="intro-top"><span class="eyebrow"><span class="live-dot"></span> SEPTEMBER 9—23, 2026</span><span class="edition">A FIRST-TIME USA ITINERARY / 01</span></div><div class="intro-title"><h1>America, <em>for the first time.</em></h1><p>Pacific mornings. Neon nights.<br>And a New York state of mind.</p></div><div class="destination-grid">{cards}</div><div class="route-strip"><span><b>15</b> days</span><span><b>3</b> city bases</span><span><b>1</b> NYC helicopter ride</span><span class="route-line">LOS ANGELES <i>→</i> LAS VEGAS <i>→</i> NEW YORK</span></div></section>
<section class="plan-note"><span class="eyebrow">THE PLAN</span><p>Go big on the moments. Leave room for the trip.<br><span>Three nights in LA, three in Vegas, eight in New York. Beach time, rooftop views, a Vegas night out, and New York from the sky.</span></p></section>
<section class="itinerary-heading" id="itinerary"><div><span class="eyebrow">YOUR DAYS, BEAUTIFULLY SPENT</span><h2>The itinerary</h2></div><div><p>Open a day for the plan, places and practical details.</p><button type="button" class="text-button" id="expand">Expand all days <span aria-hidden="true">+</span></button></div></section>
<p class="schedule-note">Suggested local-time windows · Nothing is booked · September 23 assumed to be departure day</p>
<nav class="chapter-nav" aria-label="Itinerary chapters"><a href="#la"><span>01</span> Los Angeles <small>SEP 9–12</small></a><a href="#vegas"><span>02</span> Las Vegas <small>SEP 12–15</small></a><a href="#nyc"><span>03</span> New York City <small>SEP 15–23</small></a></nav>
{chapterhtml}
<section class="bookings-section" id="bookings"><div class="section-title"><div><span class="eyebrow">A FEW THINGS TO LOCK IN</span><h2>The big-ticket moments.</h2></div><p>Check availability before fixing the order.<br>All links go to planning or booking pages; no reservations have been made.</p></div><div class="booking-grid">{bookinghtml}</div><p class="booking-foot">Vegas: {link('Sphere calendar','https://www.thesphere.com/shows/calendar')} · Rooftop: {link('230 Fifth','https://230-fifth.com/')}</p></section>
<section class="essentials" id="essentials"><div class="section-title"><div><span class="eyebrow">LESS FIGURING OUT. MORE BEING THERE.</span><h2>A few good things to know.</h2></div></div><div class="essentials-grid"><article><span class="mini-icon">↗</span><h3>Getting around</h3><p><b>LA:</b> use rideshares for city days and plan coast transport in advance. A rental is optional; at 23, confirm age rules, extra fees and accepted driving documents directly with the rental company.</p><p><b>Vegas:</b> walk small clusters of resorts, then use a taxi or rideshare. For NYC, use walking and the subway; tap the same card or device consistently. {link('Current MTA fare guidance','https://www.mta.info/fares')}</p></article><article><span class="mini-icon">◷</span><h3>Time & breathing room</h3><p>LA and Vegas are on Pacific time. NYC is three hours ahead. All itinerary windows use the destination’s local time.</p><p>LA traffic and airport transfers are the main schedule risks. Keep both flight days light. The September 18 and 22 daytime plans can absorb a weather-delayed NYC helicopter ride.</p></article><article><span class="mini-icon">$</span><h3>A planning budget</h3><p>Allow roughly <b>$650–1,100 per person</b> for the NYC helicopter, Sphere, Broadway, the Liberty ferry, one deck and a museum. This is a planning allowance, not a live quote; premium seats, nightlife and shopping can raise it.</p><p>Hotels, flights, food, local transport, shopping and optional extras are separate. Compare final totals including taxes, facility charges and Vegas resort fees.</p></article><article><span class="mini-icon">☀</span><h3>Pack for the whole day</h3><p>Comfortable walking shoes, a refillable water bottle, sunglasses, sunscreen, a light layer and a power bank will earn their space. Bring a US plug adapter and check your charger’s voltage label.</p><p>Use mobile data for maps, save tickets offline and keep an extra copy of essential travel documents. Confirm any ID requirements on flight and activity bookings.</p></article></div><div class="swap-note"><b>What we left out, on purpose</b><p>The western leg has six nights. Keep those for LA and Vegas instead of adding distant stops and hotel moves. Malibu can replace the Venice morning; Universal can replace the LA shopping day. Neither needs to become an extra obligation.</p></div></section>
<section class="sources"><details><summary>Sources, assumptions & photo credits <span>+</span></summary><div><p>Planning information checked September 5, 2026. Operator pages can change. Dates, prices, opening hours, routes and availability must be reconfirmed at booking. Flight times and day lengths are estimates; hotel and airline choices are still open.</p><p>The official sources are linked beside the relevant day and booking item. Key references: {link('National Park Service','https://www.nps.gov/stli/planyourvisit/fees.htm')}, {link('HeliNY','https://heliny.com/')}, {link('The Met','https://www.metmuseum.org/plan-your-visit')} and {link('Broadway League','https://www.broadway.org/')}.</p><div id="photo-credits">PHOTO_CREDITS</div></div></details></section>
</main><footer><a class="brand" href="#top"><span class="brand-mark">a<span>↗</span></span> THE AMERICA EDIT</a><p>September 2026 · Made for a first time, remembered for a lifetime.</p><a href="#top">Back to top ↑</a></footer></body></html>'''
credits=ROOT/'assets'/'credits.html'
html=html.replace('PHOTO_CREDITS',credits.read_text() if credits.exists() else '<p>Destination photography credits are being prepared.</p>')
(ROOT/'index.html').write_text(html)
(ROOT/'scripts'/'itinerary.json').write_text(json.dumps([{'date':f'2026-09-{d[1]:02}','city':d[0],'title':d[2]} for d in days],indent=2)+'\n')
print('Built index.html: 15 days, 3 chapters.')
