from pathlib import Path
from datetime import date
from html import escape as e
from urllib.parse import quote
import json
ROOT=Path(__file__).resolve().parent.parent
# All times are suggested local-time windows, not reservations.
days=[
('sf',9,'Hello, San Francisco','Arrival · Embarcadero · Ferry Building','Easy arrival','San Francisco',[
('After landing','Settle into the city.','Allow for immigration, luggage and your airport transfer, then check into the hotel. Stay in San Francisco for three nights; there is no need for a rental car until September 12.'),
('If arrival allows','Your first waterfront walk.','Head to the Ferry Building and Embarcadero for bay views, coffee and something to eat. Keep the walk short and choose food around the actual arrival time.'),
('Evening','Dinner, then a proper sleep.','Eat near the hotel and call it an early night. Tomorrow is the Golden Gate day, so nothing essential depends on arrival-day energy.')],
'Choose a hotel with a convenient transit connection and check the exact location before booking. Keep all arrival activities optional until the flight time is known.',
'Late arrival? Go straight to the hotel. The waterfront can fit on September 11.',['Ferry Building San Francisco','Embarcadero San Francisco'],[('Official SF visitor guide','https://www.sftravel.com/')]),
('sf',10,'Golden Gate, painted houses & city views','Golden Gate Bridge · Marina · Painted Ladies','Classic San Francisco','San Francisco',[
('Morning','The Golden Gate moment.','Head to the Golden Gate Bridge welcome area and walk part of the bridge if conditions are comfortable. Bring a layer: wind and fog can change the feel of the day. No need to cross the whole bridge.'),
('Midday','Palace of Fine Arts & Marina lunch.','Take transit or a rideshare to the Palace of Fine Arts, then find lunch and browse around Chestnut Street. Leave time for photos and a relaxed café stop.'),
('Afternoon / evening','Painted Ladies, then Hayes Valley.','Visit Alamo Square for the Painted Ladies view, then explore Hayes Valley for shops and dinner. These are separate neighborhoods; use transit between the waterfront and Alamo Square rather than walking every transfer.')],
'This is a city sightseeing day without the rental car. If the bridge is completely fogged in, exchange its visit with a clearer window tomorrow. Let the view and weather determine how long to stay.',
'If you prefer a bay-side village outing, Sausalito can replace the afternoon; check ferry times and drop the Painted Ladies and Hayes Valley rather than adding everything.',['Golden Gate Bridge Welcome Center','Palace of Fine Arts San Francisco','Chestnut Street San Francisco','Painted Ladies San Francisco','Hayes Valley'],[('SF highlights & trip planning','https://www.sftravel.com/')]),
('sf',11,'Cable cars, the bay & neighborhood bites','Alcatraz option · Pier 39 · North Beach · Cable car','Choose your bay experience','San Francisco',[
('Morning','Alcatraz, if it appeals.','Reserve the official Alcatraz island tour from Pier 33 if the history interests you. Allow most of the morning for the ferry and visit. If tickets are unavailable or it is not your thing, choose a bay cruise or a waterfront morning instead.'),
('Afternoon','Sea lions, then North Beach.','Make Pier 39 a short stop for the sea lions and bay atmosphere, then head to North Beach for a late lunch or coffee. Walk toward Chinatown if you have energy; food and neighborhood streets are the focus.'),
('Late afternoon / evening','Ride a cable car.','Work a cable-car ride into the afternoon; the California Street line is an option if you want to avoid building the day around a long turnaround queue. Finish with dinner and pack for tomorrow’s coast-and-bus travel day.')],
'Book the island visit only through the official NPS ticket link. A sightseeing cruise around Alcatraz does not include landing. Check cable-car service and fares before riding.',
'If Alcatraz is unavailable, keep the waterfront and neighborhoods. Do not spend the whole day chasing a sold-out ticket.',['Alcatraz City Cruises Pier 33','Pier 39 San Francisco','North Beach San Francisco','Chinatown San Francisco','California Street Cable Car'],[('Official Alcatraz planning & tickets','https://www.nps.gov/alca/planyourvisit/index.htm'),('Cable car visitor guide','https://www.sftravel.com/things-to-do/attractions/iconic-sf/cable-cars')]),
('sf',12,'The coast, then south overnight','SF → Santa Cruz → San Jose → LA','Connections not booked','Overnight coach to LA — provisional',[
('Morning','Collect the car & drive to Santa Cruz.','Pick up the rental early and head south. If return timing allows, use the coast via Half Moon Bay with one short stop. Allow roughly 2–3 hours of driving as a planning estimate, plus stops and traffic; check live road conditions.'),
('Midday / afternoon','A little Santa Cruz.','Lunch, the beach and a visit to the Boardwalk if its September 12 hours fit. Keep the sightseeing window subordinate to the confirmed rental-return deadline. Do not assume a Santa Cruz rental branch accepts a late Saturday return.'),
('Late afternoon / evening','Highway 17 Express to San Jose.','After the car return or handoff is settled, reach the current Santa Cruz boarding stop and take the northbound Highway 17 Express toward San Jose Diridon. Use the new fall Saturday timetable effective September 10. Target at least 90–120 minutes between scheduled arrival and the intercity departure, with more buffer if the stops differ.'),
('Late night / after midnight','Connect to the LA bus.','Book a direct overnight intercity service only after checking the exact date, pickup point, baggage allowance and LA arrival stop. A departure after midnight is September 13, even though you reach San Jose on September 12. The generic FlixBus page lists 12:35 a.m.; that is not verified availability for this trip.')],
'UNCONFIRMED: rental return or handoff in Santa Cruz, the September 12 Highway 17 departure, and the intercity ticket. This route assumes you no longer have the car before boarding Highway 17. If the car must be returned in San Jose, drive it there instead and omit Highway 17. Separate tickets are not a protected connection.',
'If the car return or overnight connection does not work, stay in San Jose on September 12 and travel September 13, accepting less LA time. Do not book a daytime LA bus that leaves before you can realistically reach San Jose. Plan a suitable waiting place around the confirmed departure; do not assume Diridon facilities stay open overnight.',['Santa Cruz Beach Boardwalk','San Jose Diridon Station'],[('Highway 17 official schedule & alerts','https://scmetro.org/routes/route-17/'),('San Jose–LA intercity options','https://www.flixbus.com/bus-routes/bus-san-jose-ca-los-angeles-ca'),('Rental one-way policy','https://www.enterprise.com/en/car-rental-faqs/us-general/one-way-car-rental-policy.html'),('Boardwalk calendar','https://beachboardwalk.com/hours/'),('Live California roads','https://quickmap.dot.ca.gov/')]),
('la',13,'A gentle LA arrival, a golden-hour finish','Bus arrival · Rest · Hollywood · Griffith','Recovery + one big highlight','Los Angeles',[
('Morning / actual arrival','Drop bags, breakfast, recover.','The arrival time and stop depend on the unbooked coach. Arrange the transfer to your LA hotel and confirm luggage storage or paid early check-in; do not assume a room will be ready after an overnight bus.'),
('Afternoon, if rested','A short Hollywood introduction.','If you feel up to it, see the Walk of Fame and TCL Chinese Theatre briefly. Otherwise take the afternoon to rest. Keep timed attractions off this arrival day.'),
('Late afternoon / evening','Griffith at sunset.','Make Griffith Observatory the one headline experience if the bus arrives in time and you feel well rested. Go before sunset for the Hollywood Sign and city lights, then dinner near your hotel. Sunday fits the published opening pattern; check live access before leaving.')],
'Stay in the same LA hotel September 13 and 14. Hollywood or West Hollywood can suit this short visit, depending on the hotel and transport budget. Griffith’s building is closed Mondays, so Sunday is the better interior-visit day.',
'If the bus is late or exhausting, skip Hollywood and prioritize rest. If Griffith also falls through, Monday can offer outdoor viewpoints subject to park access, but not a normal observatory building visit.',['TCL Chinese Theatre','Griffith Observatory'],[('Griffith hours & access','https://griffithobservatory.lacity.gov/visit/')]),
('la',14,'Beverly Hills to a Pacific sunset','Beverly Hills · Santa Monica · Optional Venice','One full LA day','Los Angeles',[
('09:30–12:00','Coffee, palms & Rodeo Drive.','Start with Beverly Gardens Park, Rodeo Drive and a café breakfast. Keep this a relaxed, compact visit rather than a long shopping day.'),
('Afternoon','Santa Monica, slowly.','Head west for lunch, the pier and time on the beach. Allow for LA traffic between neighborhoods. Santa Cruz was the classic boardwalk stop; here you get the unmistakable Santa Monica setting.'),
('Late afternoon / evening','Beach path, sunset & dinner.','If you have energy, add a short beach-path ride or a Venice visit, checking bike-return hours. Otherwise stay in Santa Monica for sunset and dinner, then return to pack for the flight to NYC.')],
'With only one full LA day, choose the experiences you most want. Universal Studios Hollywood can replace this entire day if films and rides matter more than Beverly Hills and the beach. Skip The Grove and Malibu on this shorter route.',
'Vegas is not in the main plan. A one-night September 14 detour would replace this entire LA day: travel to Vegas, one Strip evening, then fly LAS–NYC September 15. Consider it only if Vegas is a higher priority and both flights work; no extra LA day is created.',['Beverly Gardens Park','Rodeo Drive','Santa Monica Pier'],[('Optional full-day Universal alternative','https://www.universalstudioshollywood.com/web/en/us')]),
('nyc',15,'Hello, New York','Los Angeles → NYC · Times Square','Travel day','New York City',[
('Morning','Fly east.','Choose a morning nonstop if possible. Allow roughly 5–6 hours in the air from LA, and New York is 3 hours ahead, so much of the day disappears. Check whether you land at JFK, LaGuardia or Newark.'),
('Late afternoon / evening','Hotel, food, a little reset.','Allow for baggage and the airport transfer before committing to plans. Use the appropriate airport’s official transport guidance; the three airports have different routes.'),
('After dark','Your Times Square moment.','If arrival allows, make a short visit to Times Square. Get the photos, take in the lights and have dinner. Save the full sightseeing day for tomorrow.')],
'Use one NYC hotel for eight nights. Midtown West, Chelsea or a well-connected Midtown location makes a practical base. Compare total hotel costs, subway access and recent reviews before choosing.',
'Late flight? Move Times Square to another evening. There is no paid reservation today.',['Times Square, New York'],[('NYC airport transport','https://www.panynj.gov/airports/en/index.html')]),
('nyc',16,'The city, with room to wander','Chelsea · High Line · West Village','First full NYC day','New York City',[
('10:00–12:00','Chelsea Market lunch crawl.','Start with coffee and browse the food stalls. Pick lunch when something looks good instead of building the day around a hard-to-get reservation.'),
('13:00–16:00','High Line & Little Island.','Walk a manageable stretch of the High Line, then head toward Little Island. Stop for river views, take breaks and check park access before setting off.'),
('Evening','West Village dinner.','Wander the smaller streets, see Washington Square Park and find dinner in the Village. Reserve ahead if there is a particular restaurant you really want.')],
'Start with neighborhoods and river views rather than a packed landmark checklist. If you prefer a hop-on/hop-off bus introduction, use it instead of the afternoon walk; check current routes and stops.',
'Rain? Replace the outdoor walk with a museum visit or a long Chelsea Market lunch.',['Chelsea Market','The High Line','Little Island NYC','Washington Square Park'],[('High Line hours & access','https://www.thehighline.org/visit/'),('Little Island visitor information','https://littleisland.org/visit-us/'),('Optional sightseeing bus','https://www.bigbustours.com/en/new-york/new-york-bus-tours')]),
('nyc',17,'Meet Lady Liberty','Liberty Island · Ellis Island · Lower Manhattan','Book ahead','New York City',[
('08:30–09:30 target','Ferry from The Battery.','Reserve a morning Statue City Cruises departure from New York, not New Jersey. Follow the ticket’s screening and arrival instructions. The selected ticket time relates to entry into screening, not a guaranteed ferry departure.'),
('Morning / early afternoon','Liberty Island & Ellis Island.','Allow about 4–5 hours overall, longer for deep museum visits. Choose pedestal or crown only if available and suitable; the standard island visit is still worthwhile. Ellis Island adds context to America’s immigration story.'),
('Late afternoon','Lower Manhattan, at your pace.','If energy allows, walk past Wall Street and visit the outdoor 9/11 Memorial respectfully. The museum is a separate, longer visit. Skip an extra observation deck; Top of the Rock is already planned.')],
'Statue City Cruises is the only authorized ferry that lands visitors on both islands. Book through the official NPS link. Pedestal and crown inventory is limited; do not buy a harbor sightseeing cruise expecting island access.',
'If island tickets are sold out, a harbor sightseeing cruise can give views but is not a substitute for landing. Keep checking official availability.',['The Battery, New York','Wall Street, New York','9/11 Memorial'],[('Official ferry & ticket guidance','https://www.nps.gov/stli/planyourvisit/fees.htm'),('Screening & arrival information','https://www.nps.gov/stli/planyourvisit/index.htm')]),
('nyc',18,'New York, from the sky.','NYC helicopter · Seaport · Waterfront','Must-do flight','New York City',[
('Morning','A relaxed start downtown.','Have breakfast, then head toward the confirmed Downtown Manhattan heliport. Leave the morning flexible around the actual flight slot; avoid any distant timed attraction beforehand.'),
('Early afternoon','The skyline from the Hudson.','Aim for a HeliNY Downtown Manhattan departure, such as its 17–20 minute Ultimate Tour. Reach the heliport independently, allowing transit time plus the required check-in. Confirm the exact address on your reservation.'),
('Late afternoon / evening','Seaport & the waterfront.','Keep the rest of the day nearby: a Seaport stroll, waterfront views and a relaxed dinner. The helicopter is the headline; no need to race straight to the opposite end of Manhattan.')],
'Schedule the ride for Friday, September 18, with Saturday, September 19 as the only backup date. Confirm availability and the weather-change policy before paying. Downtown sightseeing routes follow the river for skyline views; they are not flights between Midtown buildings. HeliNY also sells New Jersey departures—check the departure location carefully.',
'If September 18 is canceled, try September 19 with the operator. Move that day’s park and observation-deck plans as needed. If neither date is flyable or available, discuss the refund options; do not move the ride outside these two dates.',['Downtown Manhattan Heliport','South Street Seaport'],[('NYC helicopter tours & fees','https://heliny.com/')]),
('nyc',19,'Park greens, skyline gold','Central Park · Fifth Avenue · Top of the Rock','Helicopter backup date','New York City',[
('09:30–12:30','A slow Central Park morning.','Walk the Mall, Bethesda Terrace and Bow Bridge. Take a coffee break and leave time simply to sit. You do not need to cover the entire park.'),
('14:00–16:30','Fifth Avenue icons.','Head south for Fifth Avenue, St. Patrick’s Cathedral and Rockefeller Center. This groups the sights naturally without repeated subway trips.'),
('Late afternoon / sunset','Top of the Rock.','Reserve a time before sunset if the forecast is good. You get the Empire State Building in the skyline rather than standing inside it. Sunset slots can cost more and fill up.')],
'Keep September 19 available as the helicopter backup. If the flight moves here, prioritize it and shift Central Park or Top of the Rock to September 22 daytime, choosing a deck slot that leaves enough time for Broadway. Avoid a non-changeable deck ticket until the flight is settled.',
'If the helicopter flew on September 18, enjoy the full park-and-skyline day. If it moves to today, use the confirmed flight slot to rebuild the day rather than squeezing everything in.',['Bethesda Terrace','Bow Bridge','St. Patrick’s Cathedral New York','Top of the Rock'],[('Top of the Rock official tickets','https://www.rockefellercenter.com/tickets/top-of-the-rock-observation-deck')]),
('nyc',20,'Across the bridge, into Brooklyn','Brooklyn Bridge · DUMBO · Waterfront','Photo day','New York City',[
('09:00–10:30','Walk the Brooklyn Bridge.','Start on the Manhattan side and cross to Brooklyn. Go early for a calmer walk, keep the path clear for others and leave plenty of time for photos.'),
('11:00–15:00','DUMBO & Brooklyn Bridge Park.','Find the Washington Street view, have lunch around DUMBO and wander the waterfront. Take photos from the sidewalk rather than standing in traffic.'),
('Late afternoon / evening','The skyline from the other side.','Continue to Brooklyn Heights Promenade if your feet are happy. Stay for the light changing over Manhattan, then take the subway or a ferry with a confirmed return route.')],
'Wear your most comfortable shoes. A ferry can be a lovely finish, but check the current route and last departure first; NYC Ferry uses separate tickets from the subway.',
'If it rains heavily, move this walk to September 22 and use today for an indoor choice.',['Brooklyn Bridge Manhattan entrance','Washington Street DUMBO','Brooklyn Bridge Park','Brooklyn Heights Promenade'],[('NYC Ferry routes & tickets','https://www.ferry.nyc/')]),
('nyc',21,'Art, architecture, a New York evening','The Met · Grand Central · Bryant Park','Culture day','New York City',[
('10:00–13:00','Choose a few galleries at The Met.','Spend the morning at the Metropolitan Museum of Art. Choose two or three collections rather than trying to see everything. Monday fits its published weekly schedule; the museum is closed Wednesdays.'),
('14:30–17:00','Grand Central & Bryant Park.','Take transit to Grand Central, then walk to Bryant Park and the New York Public Library’s main building. Check visitor access and tour times if you want to go inside.'),
('Evening','Dinner & a rooftop view.','Have dinner, then try a rooftop such as 230 Fifth for the Empire State Building backdrop if the weather is good. Check that evening’s opening and entry rules. A mocktail and the view are just as much the point as a cocktail.')],
'The Met is the default museum choice. If natural history appeals more, swap in the American Museum of Natural History and check its entry requirements. Avoid scheduling both museums in one day.',
'This is also a good rainy-day plan to exchange with September 19 or 20, provided the chosen museum is open.',['The Metropolitan Museum of Art','Grand Central Terminal','Bryant Park'],[('The Met visitor information','https://www.metmuseum.org/plan-your-visit'),('NYPL visitor information','https://www.nypl.org/locations/schwarzman'),('230 Fifth rooftop','https://230-fifth.com/')]),
('nyc',22,'One more neighborhood. One big finale.','SoHo · Chinatown · Broadway','Flexible day + curtain call','New York City',[
('Late morning','SoHo, without a checklist.','Coffee, shopping, cast-iron streets and time to explore. This is intentionally a loose morning for whatever you still want to do.'),
('Afternoon','Chinatown lunch, or your missed favorite.','Walk to Chinatown for lunch and pass through Little Italy if you are curious. Alternatively use the daytime for Central Park or Top of the Rock if they moved from September 19, a Brooklyn walk or a favorite place you want to revisit. Leave a generous buffer before Broadway.'),
('Evening','Your Broadway night.','Book a Tuesday performance through the show’s official ticket link. Choose a story or music you already like; a visual musical can be a fun first choice. Eat nearby and arrive according to the theater’s guidance.')],
'Protect the show’s curtain time when rearranging the day. The Broadway League’s directory links to official show sites; the exact performance and ticket availability still need confirmation.',
'If your preferred show is unavailable, choose another listed Tuesday performance or move Broadway to an earlier evening after checking its calendar.',['SoHo New York','Chinatown Manhattan','Theater District Manhattan'],[('Broadway official show directory','https://www.broadway.org/')]),
('nyc',23,'A last coffee, then home','NYC → onward journey','Departure day','Departure',[
('Morning, if time permits','One small goodbye.','Breakfast near the hotel and a short local walk. Keep luggage storage and checkout in mind. No major attraction or nonrefundable booking today.'),
('Before your flight','Give the airport its time.','Build the transfer around your actual departure airport and airline guidance. For an international flight, plan to reach the airport around 3 hours early, with travel time and a traffic buffer added on top.'),
('If leaving late','A bonus few hours.','Use any genuine spare time for a nearby café, a final shop or a familiar park. Return to collect luggage well before your planned airport transfer.')],
'The trip ends September 23 in this plan, following the requested dates. If the flight is actually September 24, September 23 becomes a full flexible day and one extra hotel night is needed.',
'An early flight means breakfast to go and a direct airport transfer.',['New York City'],[])
]
chapters=[('sf','01','San Francisco','The bay. The bridge. The open coast.','September 9–12 · 3 nights + onward travel','sf.jpg','Golden Gate Bridge over San Francisco Bay','Three nights in SF, then Santa Cruz and a provisional overnight connection to LA.'),('la','02','Los Angeles','Palm trees, Pacific light.','September 13–15 · 2 nights','la.jpg','Palm-lined Los Angeles streets','Recover after the coach, catch Griffith at sunset and enjoy one full LA day.'),('nyc','03','New York City','The city you already know by heart.','September 15–23 · 8 nights','nyc.jpg','Manhattan skyline across the water','Eight nights for the icons, the neighborhoods and the little things in between.')]


def link(label,url): return f'<a href="{e(url,quote=True)}" target="_blank" rel="noopener noreferrer">{e(label)} <span aria-hidden="true">↗</span></a>'
def render_day(d):
    region,day,title,route,tag,stay,slots,note,backup,places,links=d
    dt=date(2026,9,day)
    timeline=''.join(f'<li><span class="time">{e(t)}</span><div><h4>{e(h)}</h4><p>{e(p)}</p></div></li>' for t,h,p in slots)
    maplinks=''.join(link(p,'https://www.google.com/maps/search/?api=1&query='+quote(p)) for p in places)
    return f'''<details class="day" id="day-{day}" {'open' if day in (9,12,13,15) else ''}>
<summary><span class="date"><b>{day:02}</b><span>SEP · {dt.strftime('%a').upper()}</span></span><span class="day-heading"><span class="day-route">{e(route)}</span><h3>{e(title)}</h3></span><span class="tag">{e(tag)}</span><span class="toggle" aria-hidden="true">+</span></summary>
<div class="day-content"><ol class="timeline">{timeline}</ol><aside class="day-aside"><span class="eyebrow">MAKE IT WORK</span><p>{e(note)}</p><div class="backup"><b>Keep it flexible</b><p>{e(backup)}</p></div><span class="stay">◷ &nbsp; Overnight: {e(stay)}</span></aside><div class="day-links"><div><b>Places on the map</b><div>{maplinks}</div></div>{('<div><b>Plan & book</b><div>'+''.join(link(l,u) for l,u in links)+'</div></div>') if links else ''}</div></div></details>'''

chapterhtml=''
for key,num,name,title,dates,img,alt,intro in chapters:
    chapterhtml+=f'''<section class="chapter" id="{key}" aria-labelledby="heading-{key}"><div class="chapter-head"><div><span class="eyebrow">CHAPTER {num} / {e(dates).upper()}</span><h2 id="heading-{key}">{e(name)}<span class="dot">.</span></h2><p>{e(intro)}</p></div><a class="back" href="#route">Back to route ↑</a></div><div class="chapter-banner"><img src="assets/{img}" alt="{e(alt)}" loading="lazy" width="1600" height="1000"><p>{e(title)}</p></div><div class="day-list">{''.join(render_day(d) for d in days if d[0]==key)}</div></section>'''
bookings=[('01','Statue of Liberty','September 17','Start with official island tickets. Choose New York departure; pedestal or crown only if available. Standard island access is a good fallback.','Official ticket guidance','https://www.nps.gov/stli/planyourvisit/fees.htm'),('02','Manhattan from the sky.','September 18 · Backup September 19','The trip’s helicopter ride. Confirm a Manhattan departure, total charges and weather policy. The ride must be on September 18 or 19. Plan for the 18th and keep the 19th flexible; availability is not yet confirmed.','NYC operator','https://heliny.com/'),('03','Make the coast connection work.','September 12–13 · Not booked','Confirm the rental return first, then the new Saturday Highway 17 schedule and the overnight LA coach. After-midnight departure means a September 13 ticket.','Intercity route & booking','https://www.flixbus.com/bus-routes/bus-san-jose-ca-los-angeles-ca'),('04','The golden-hour skyline','September 19','Top of the Rock is the one planned observation deck. Check the weather and ticket-change policy before choosing your time.','Official deck tickets','https://www.rockefellercenter.com/tickets/top-of-the-rock-observation-deck')]
bookinghtml=''.join(f'<article class="booking"><span class="booking-num">{n}</span><span class="eyebrow">{e(dt)}</span><h3>{e(title)}</h3><p>{e(desc)}</p>{link(label,url)}</article>' for n,title,dt,desc,label,url in bookings)
cards=''.join(f'<a class="destination {key}" href="#{key}"><img src="assets/{img}" alt="{e(alt)}" width="1600" height="1000" {"fetchpriority=\"high\"" if key=="sf" else ""}><span class="card-top"><span>CHAPTER {num}</span><span>↗</span></span><span class="card-bottom"><span>{e(dates)}</span><strong>{e(name)}</strong></span></a>' for key,num,name,title,dates,img,alt,intro in chapters)
html=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#172c36"><title>Sofia’s American Adventure — September 9–23, 2026</title><meta name="description" content="Sofia’s 15-day journey through San Francisco, Santa Cruz, Los Angeles and New York. A thoughtful daily itinerary with an NYC helicopter ride, the Statue of Liberty, beach days and city nights."><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;450;500;600;650;700&family=Manrope:wght@400;500;600;700;800&family=Playfair+Display:ital,wght@1,500&display=swap" rel="stylesheet"><link rel="stylesheet" href="styles.css"><script src="app.js" defer></script></head>
<body><a class="skip" href="#itinerary">Skip to daily itinerary</a><header><a class="brand" href="#top"><span class="brand-mark">s<span>↗</span></span> SOFIA’S AMERICAN ADVENTURE</a><nav aria-label="Main navigation"><a href="#route">The route</a><a href="#itinerary">Day by day</a><a href="#bookings">Book ahead</a><a href="#essentials">Good to know</a></nav><button class="print-button" type="button" id="print">Print guide <span aria-hidden="true">↗</span></button></header>
<main id="top"><section class="intro" id="route"><div class="intro-top"><span class="eyebrow"><span class="live-dot"></span> SEPTEMBER 9—23, 2026</span><span class="edition">A FIRST-TIME USA ITINERARY / 01</span></div><div class="intro-title"><h1>Sofia’s <em>American adventure.</em></h1><p>San Francisco mornings. Pacific sunsets.<br>And a New York state of mind.</p></div><div class="destination-grid">{cards}</div><div class="route-strip"><span><b>15</b> days</span><span><b>3</b> city bases</span><span><b>1</b> NYC helicopter ride</span><span class="route-line">SAN FRANCISCO <i>→</i> LOS ANGELES <i>→</i> NEW YORK</span></div></section>
<section class="plan-note"><span class="eyebrow">THE PLAN</span><p>Go big on the moments. Leave room for the trip.<br><span>Three nights in San Francisco, a Santa Cruz day and overnight coach, two nights in LA, then eight in New York. The September 12 connections are provisional; Vegas stays outside the main route.</span></p></section>
<section class="itinerary-heading" id="itinerary"><div><span class="eyebrow">YOUR DAYS, BEAUTIFULLY SPENT</span><h2>The itinerary</h2></div><div><p>Open a day for the plan, places and practical details.</p><button type="button" class="text-button" id="expand">Expand all days <span aria-hidden="true">+</span></button></div></section>
<p class="schedule-note">Suggested local-time windows · Nothing is booked · September 23 assumed to be departure day</p>
<nav class="chapter-nav" aria-label="Itinerary chapters"><a href="#sf"><span>01</span> San Francisco <small>SEP 9–12</small></a><a href="#la"><span>02</span> Los Angeles <small>SEP 13–15</small></a><a href="#nyc"><span>03</span> New York City <small>SEP 15–23</small></a></nav>
{chapterhtml}
<section class="bookings-section" id="bookings"><div class="section-title"><div><span class="eyebrow">A FEW THINGS TO LOCK IN</span><h2>The big-ticket moments.</h2></div><p>Check availability before fixing the order.<br>All links go to planning or booking pages; no reservations have been made.</p></div><div class="booking-grid">{bookinghtml}</div><p class="booking-foot">SF: {link('Alcatraz official tickets','https://www.nps.gov/alca/planyourvisit/index.htm')} · NYC: {link('Broadway official shows','https://www.broadway.org/')} · Rooftop: {link('230 Fifth','https://230-fifth.com/')}</p></section>
<section class="essentials" id="essentials"><div class="section-title"><div><span class="eyebrow">LESS FIGURING OUT. MORE BEING THERE.</span><h2>A few good things to know.</h2></div></div><div class="essentials-grid"><article><span class="mini-icon">↗</span><h3>Getting around</h3><p><b>SF:</b> walk, use transit and take occasional rideshares until September 12. <b>Coast day:</b> confirm the car return before buying onward transport. For the planned rental, at 23, confirm age rules, extra fees and accepted driving documents directly with the rental company.</p><p><b>LA:</b> group stops geographically and budget for transfers. For NYC, use walking and the subway; tap the same card or device consistently. {link('Current MTA fare guidance','https://www.mta.info/fares')}</p></article><article><span class="mini-icon">◷</span><h3>Time & breathing room</h3><p>San Francisco, Santa Cruz, San Jose and LA are on Pacific time. NYC is three hours ahead. All itinerary windows use the destination’s local time.</p><p>The September 12 car return and two-bus connection are the main schedule risks. An overnight coach may leave you tired; keep September 13 light. The NYC helicopter is planned for September 18, with September 19 as the only backup. September 22 can absorb displaced walking or observation-deck plans, but not the helicopter.</p></article><article><span class="mini-icon">$</span><h3>A planning budget</h3><p>Allow roughly <b>$550–950 per person</b> for Alcatraz, the NYC helicopter, Broadway, the Liberty ferry, one deck and a museum. This is a planning allowance, not a live quote; premium seats, optional attractions and shopping can raise it.</p><p>Hotels, the rental car, one-way and young-driver fees, both bus legs, flights, food, local transport and shopping are separate. Compare final totals including taxes and facility charges.</p></article><article><span class="mini-icon">☀</span><h3>Pack for the whole day</h3><p>Comfortable walking shoes, a refillable water bottle, sunglasses, sunscreen, a light layer and a power bank will earn their space. Bring a US plug adapter and check your charger’s voltage label.</p><p>Use mobile data for maps, save tickets offline and keep an extra copy of essential travel documents. Confirm any ID requirements on flight and activity bookings.</p></article></div><div class="swap-note"><b>What we left out, on purpose</b><p>Recommendation: skip Vegas. The western leg now has three SF hotel nights, one provisional coach night and two LA hotel nights. A one-night Vegas option on September 14 costs the full LA beach-and-Beverly-Hills day and requires LA–LAS and LAS–NYC flights that fit. Choose that trade only if one Vegas evening matters more than a full LA day.</p></div></section>
<section class="sources"><details><summary>Sources, assumptions & photo credits <span>+</span></summary><div><p>Planning information checked September 5, 2026. Operator pages can change. Dates, prices, opening hours, routes and availability must be reconfirmed at booking. Flight times and day lengths are estimates; hotel and airline choices are still open.</p><p>The official sources are linked beside the relevant day and booking item. Key references: {link('National Park Service','https://www.nps.gov/stli/planyourvisit/fees.htm')}, {link('HeliNY','https://heliny.com/')}, {link('The Met','https://www.metmuseum.org/plan-your-visit')} and {link('Broadway League','https://www.broadway.org/')}.</p><div id="photo-credits">PHOTO_CREDITS</div></div></details></section>
</main><footer><a class="brand" href="#top"><span class="brand-mark">s<span>↗</span></span> SOFIA’S AMERICAN ADVENTURE</a><p>September 2026 · Made for a first time, remembered for a lifetime.</p><a href="#top">Back to top ↑</a></footer></body></html>'''
credits=ROOT/'assets'/'credits.html'
html=html.replace('PHOTO_CREDITS',credits.read_text() if credits.exists() else '<p>Destination photography credits are being prepared.</p>')
(ROOT/'index.html').write_text(html)
(ROOT/'scripts'/'itinerary.json').write_text(json.dumps([{'date':f'2026-09-{d[1]:02}','city':d[0],'title':d[2]} for d in days],indent=2)+'\n')
print('Built index.html: 15 days, 3 chapters.')
